#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: WiQiPedia
  fr: WiQiPedia
  zh: WiQiPedia
footer_name:
  en: Contact
  fr: Contact
  zh: Contact
email: qi.chen.1@ulaval.ca
description:
  en:
  fr:
  zh:
index:
  en:
  fr: accueil.html
  zh:
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: livreq
github_username:  livreq
linkedin: qichen

# Build settings
markdown: kramdown
